# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='time_stamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
