# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_worklog_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
