# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklog', '0003_auto_20180211_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
