# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_worklog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='project_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
